services:
  postgres:
    image: postgres:17
    container_name: soccer-postgres

    environment:
      POSTGRES_DB: soccer_db
      POSTGRES_USER: soccer
      POSTGRES_PASSWORD: soccer123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: