spring.application.name=a3_soccer
logging.level.org.springframework.cache=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5432/soccer_db
spring.datasource.username=soccer
spring.datasource.password=soccer123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.api.delay-ms=500
